name: ci-build
on: push
jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: sbt build
        run: sbt +test
